In [1]:
import json
import glob
import os
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', None)

In [2]:
results_dir = "results/again3"
files = sorted(glob.glob(os.path.join(results_dir, "*.json")))

records = []
for file in files:
    with open(file, "r") as f:
        data = json.load(f)

    filename = os.path.basename(file).lower()

    # model name 결정
    if "wo_struct" in filename:
        model_name = "scl w/o struct"
    elif "wo_potential" in filename:
        model_name = "scl w/o potential"
    elif "wo_semantic" in filename:
        model_name = "scl w/o semantic"
    elif "scl_seed" in filename:
        model_name = "scl"
    else:
        model_name = data["model"].lower()

    row = {
        "file": os.path.basename(file),
        "model": model_name,
        "dataset": data.get("dataset"),
        "seed": data.get("seed"),
        "training_time": data.get("training_time"),
        "num_parameters": data.get("num_parameters"),
    }

    for k, v in data["test_result"].items():
        row[k.lower()] = v

    records.append(row)

df = pd.DataFrame(records)
df

,file,model,dataset,seed,training_time,num_parameters,recall@1,recall@2,recall@3,recall@4,...,precision@50,map@1,map@2,map@3,map@4,map@5,map@10,map@20,map@30,map@50
0,lightgcn_lightgcn_seed2020.json,lightgcn,travel,2020,22.095090,144448,0.1502,0.2378,0.2849,0.3225,...,0.0306,0.2411,0.2357,0.2346,0.2381,0.2404,0.2550,0.2675,0.2723,0.2772
1,lightgcn_lightgcn_seed2021.json,lightgcn,travel,2021,19.418323,144448,0.1533,0.2465,0.2913,0.3352,...,0.0307,0.2471,0.2434,0.2417,0.2470,0.2509,0.2646,0.2760,0.2805,0.2854
2,lightgcn_lightgcn_seed2022.json,lightgcn,travel,2022,6.866117,144448,0.1424,0.2466,0.2874,0.3242,...,0.0310,0.2306,0.2354,0.2342,0.2363,0.2407,0.2558,0.2678,0.2734,0.2781
3,lightgcn_lightgcn_seed2023.json,lightgcn,travel,2023,9.588507,144448,0.1403,0.2365,0.2822,0.3301,...,0.0314,0.2284,0.2288,0.2289,0.2348,0.2389,0.2558,0.2664,0.2729,0.2776
4,lightgcn_lightgcn_seed2024.json,lightgcn,travel,2024,15.631820,144448,0.1420,0.2371,0.2870,0.3219,...,0.0310,0.2394,0.2335,0.2327,0.2354,0.2383,0.2547,0.2654,0.2703,0.2757
5,ncl_ncl_seed2020.json,ncl,travel,2020,81.933293,144448,0.1716,0.2562,0.3174,0.3580,...,0.0327,0.2884,0.2734,0.2737,0.2773,0.2810,0.2958,0.3078,0.3132,0.3175
6,ncl_ncl_seed2021.json,ncl,travel,2021,15.203826,144448,0.1359,0.2460,0.3011,0.3418,...,0.0310,0.2295,0.2351,0.2369,0.2410,0.2453,0.2581,0.2714,0.2767,0.2807
7,ncl_ncl_seed2022.json,ncl,travel,2022,14.692227,144448,0.1402,0.2336,0.2869,0.3259,...,0.0316,0.2295,0.2285,0.2319,0.2348,0.2393,0.2547,0.2689,0.2733,0.2783
8,ncl_ncl_seed2023.json,ncl,travel,2023,15.502902,144448,0.1419,0.2363,0.2861,0.3282,...,0.0312,0.2278,0.2298,0.2313,0.2359,0.2410,0.2573,0.2692,0.2747,0.2792
9,ncl_ncl_seed2024.json,ncl,travel,2024,17.205791,144448,0.1426,0.2374,0.2877,0.3223,...,0.0312,0.2389,0.2334,0.2330,0.2358,0.2392,0.2561,0.2667,0.2720,0.2771
10,scl_scl_seed2020.json,scl,travel,2020,86.668905,144448,0.1699,0.2554,0.3145,0.3602,...,0.0329,0.2862,0.2722,0.2725,0.2772,0.2826,0.2958,0.3084,0.3136,0.3180
11,scl_scl_seed2021.json,scl,travel,2021,14.906597,144448,0.1528,0.2403,0.2930,0.3320,...,0.0308,0.2455,0.2400,0.2413,0.2455,0.2504,0.2634,0.2768,0.2822,0.2862
12,scl_scl_seed2022.json,scl,travel,2022,16.532546,144448,0.1464,0.2461,0.2870,0.3246,...,0.0311,0.2356,0.2386,0.2371,0.2401,0.2435,0.2584,0.2711,0.2764,0.2811
13,scl_scl_seed2023.json,scl,travel,2023,16.007815,144448,0.1324,0.2385,0.2859,0.3280,...,0.0312,0.2196,0.2254,0.2267,0.2308,0.2374,0.2525,0.2647,0.2707,0.2748
14,scl_scl_seed2024.json,scl,travel,2024,15.589454,144448,0.1421,0.2342,0.2830,0.3239,...,0.0311,0.2389,0.2321,0.2311,0.2355,0.2394,0.2555,0.2681,0.2731,0.2776
15,scl_wo_potential_seed2020.json,scl w/o potential,travel,2020,86.649687,144448,0.1697,0.2549,0.3140,0.3601,...,0.0329,0.2856,0.2713,0.2721,0.2768,0.2817,0.2958,0.3079,0.3131,0.3176
16,scl_wo_potential_seed2021.json,scl w/o potential,travel,2021,15.291806,144448,0.1528,0.2403,0.2930,0.3318,...,0.0308,0.2455,0.2400,0.2413,0.2455,0.2502,0.2634,0.2768,0.2821,0.2861
17,scl_wo_potential_seed2022.json,scl w/o potential,travel,2022,16.291900,144448,0.1464,0.2461,0.2867,0.3241,...,0.0311,0.2356,0.2386,0.2369,0.2399,0.2434,0.2583,0.2710,0.2763,0.2810
18,scl_wo_potential_seed2023.json,scl w/o potential,travel,2023,15.705359,144448,0.1324,0.2385,0.2860,0.3276,...,0.0312,0.2196,0.2254,0.2267,0.2307,0.2373,0.2524,0.2647,0.2707,0.2748
19,scl_wo_potential_seed2024.json,scl w/o potential,travel,2024,15.400355,144448,0.1421,0.2348,0.2836,0.3245,...,0.0311,0.2389,0.2324,0.2313,0.2357,0.2396,0.2557,0.2682,0.2732,0.2778
20,scl_wo_semantic_seed2020.json,scl w/o semantic,travel,2020,15.876499,144448,0.1430,0.2432,0.2862,0.3247,...,0.0307,0.2328,0.2349,0.2328,0.2363,0.2398,0.2543,0.2669,0.2729,0.2768
21,scl_wo_semantic_seed2021.json,scl w/o semantic,travel,2021,14.787010,144448,0.1477,0.2375,0.2937,0.3318,...,0.0310,0.2405,0.2360,0.2391,0.2426,0.2481,0.2616,0.2751,0.2804,0.2843
22,scl_wo_semantic_seed2022.json,scl w/o semantic,travel,2022,19.532907,144448,0.1442,0.2477,0.2903,0.3289,...,0.0312,0.2350,0.2389,0.2371,0.2400,0.2434,0.2577,0.2704,0.2753,0.2804
23,scl_wo_semantic_seed2023.json,scl w/o semantic,travel,2023,15.942109,144448,0.1367,0.2395,0.2903,0.3290,...,0.0312,0.2262,0.2284,0.2302,0.2341,0.2400,0.2564,0.2688,0.2746,0.2786
24,scl_wo_semantic_seed2024.json,scl w/o semantic,travel,2024,16.084008,144448,0.1378,0.2369,0.2874,0.3236,...,0.0312,0.2334,0.2313,0.2309,0.2336,0.2372,0.2532,0.2656,0.2711,0.2757
25,scl_wo_struct_seed2020.json,scl w/o struct,travel,2020,6.640458,144448,0.1396,0.2355,0.2825,0.3232,...,0.0304,0.2256,0.2263,0.2273,0.2316,0.2356,0.2494,0.2612,0.2665,0.2711
26,scl_wo_struct_seed2021.json,scl w/o struct,travel,2021,10.062417,144448,0.1539,0.2472,0.2926,0.3371,...,0.0308,0.2477,0.2444,0.2426,0.2474,0.2516,0.2643,0.2763,0.2817,0.2865
27,scl_wo_struct_seed2022.json,scl w/o struct,travel,2022,11.608326,144448,0.1448,0.2456,0.2903,0.3365,...,0.0310,0.2361,0.2372,0.2362,0.2410,0.2430,0.2575,0.2700,0.2755,0.2802
28,scl_wo_struct_seed2023.json,scl w/o struct,travel,2023,8.633749,144448,0.1431,0.2353,0.2821,0.3286,...,0.0313,0.2312,0.2292,0.2300,0.2353,0.2397,0.2558,0.2674,0.2738,0.2784
29,scl_wo_struct_seed2024.json,scl w/o struct,travel,2024,10.754975,144448,0.1431,0.2374,0.2862,0.3231,...,0.0312,0.2405,0.2339,0.2322,0.2352,0.2383,0.2545,0.2657,0.2713,0.2764

In [3]:
df.groupby("model")[["recall@10", "ndcg@10", "precision@10", "map@10", "training_time"]].agg(["mean", "std"])

                  recall@10            ndcg@10           precision@10  \
                       mean       std     mean       std         mean
model
lightgcn            0.47796  0.011493  0.33716  0.004623      0.08682
ncl                 0.48812  0.013916  0.34540  0.017353      0.09056
scl                 0.48604  0.014409  0.34538  0.017226      0.08996
scl w/o potential   0.48672  0.015937  0.34552  0.017535      0.09000
scl w/o semantic    0.47764  0.010113  0.33682  0.003846      0.08750
scl w/o struct      0.47456  0.009324  0.33570  0.005743      0.08602

                              map@10           training_time
                        std     mean       std          mean        std
model
lightgcn           0.001195  0.25718  0.004176     14.719971   6.428711
ncl                0.005189  0.26440  0.017600     28.907608  29.657261
scl                0.005545  0.26512  0.017615     29.941063  31.717407
scl w/o potential  0.005687  0.26512  0.017616     29.867821  31.744405
scl w/o semantic   0.001629  0.25664  0.003282     16.444507   1.802118
scl w/o struct     0.000960  0.25630  0.005398      9.539985   1.952927

In [10]:
summary = df.groupby("model")[["recall@1","recall@2","recall@3","recall@4","recall@5","recall@10","recall@20","recall@30","recall@50",
                               "precision@1","precision@2","precision@3","precision@4","precision@5","precision@10","precision@20","precision@30","precision@50",
                               "ndcg@1","ndcg@2","ndcg@3","ndcg@4","ndcg@5","ndcg@10","ndcg@20","ndcg@30","ndcg@50",
                               "map@1","map@2","map@3","map@4","map@5","map@10","map@20","map@30","map@50",
                               "training_time","num_parameters"]].agg(["mean","std"])

mean_cols = summary.xs('mean', level=1, axis=1)

summary["recall_avg"] = mean_cols[[col for col in mean_cols.columns if "recall@" in col]].mean(axis=1)
summary["recall_std"] = mean_cols[[col for col in mean_cols.columns if "recall@" in col]].std(axis=1)
summary["precision_avg"] = mean_cols[[col for col in mean_cols.columns if "precision@" in col]].mean(axis=1)
summary["precision_std"] = mean_cols[[col for col in mean_cols.columns if "precision@" in col]].std(axis=1)
summary["ndcg_avg"] = mean_cols[[col for col in mean_cols.columns if "ndcg@" in col]].mean(axis=1)
summary["ndcg_std"] = mean_cols[[col for col in mean_cols.columns if "ndcg@" in col]].std(axis=1)
summary["map_avg"] = mean_cols[[col for col in mean_cols.columns if "map@" in col]].mean(axis=1)
summary["map_std"] = mean_cols[[col for col in mean_cols.columns if "map@" in col]].std(axis=1)

summary

                  recall@1           recall@2           recall@3            \
                      mean       std     mean       std     mean       std
model
lightgcn           0.14564  0.005739  0.24090  0.005178  0.28656  0.003359
ncl                0.14644  0.014304  0.24190  0.009244  0.29584  0.013542
scl                0.14872  0.013971  0.24290  0.008190  0.29268  0.012729
scl w/o potential  0.14868  0.013896  0.24292  0.007842  0.29266  0.012424
scl w/o semantic   0.14188  0.004582  0.24096  0.004501  0.28958  0.002924
scl w/o struct     0.14490  0.005375  0.24020  0.005747  0.28674  0.004659

                  recall@4           recall@5            ... num_parameters  \
                      mean       std     mean       std  ...           mean
model                                                    ...
lightgcn           0.32678  0.005716  0.35874  0.009051  ...       144448.0
ncl                0.33524  0.014708  0.36862  0.015176  ...       144448.0
scl                0.33374  0.015137  0.37136  0.018023  ...       144448.0
scl w/o potential  0.33362  0.015121  0.37064  0.017065  ...       144448.0
scl w/o semantic   0.32760  0.003380  0.36188  0.008181  ...       144448.0
scl w/o struct     0.32970  0.006856  0.36040  0.007761  ...       144448.0

                       recall_avg recall_std precision_avg precision_std  \
                   std
model
lightgcn           0.0   0.433282   0.214761      0.119304      0.070715
ncl                0.0   0.441351   0.217326      0.123989      0.072706
scl                0.0   0.441351   0.216919      0.124158      0.073189
scl w/o potential  0.0   0.441231   0.216875      0.124089      0.073147
scl w/o semantic   0.0   0.435033   0.216082      0.119951      0.069839
scl w/o struct     0.0   0.434513   0.216291      0.118967      0.070351

                   ndcg_avg  ndcg_std   map_avg   map_std

model
lightgcn           0.319762  0.062778  0.251749  0.017998
ncl                0.327593  0.063936  0.258676  0.018905
scl                0.328433  0.063676  0.259858  0.018770
scl w/o potential  0.328324  0.063684  0.259753  0.018784
scl w/o semantic   0.319956  0.064114  0.251171  0.019002
scl w/o struct     0.319520  0.063332  0.251169  0.018206

[6 rows x 84 columns]

In [11]:
data = pd.DataFrame(summary).T
data

model                     lightgcn            ncl            scl  \
recall@1       mean       0.145640       0.146440       0.148720
               std        0.005739       0.014304       0.013971
recall@2       mean       0.240900       0.241900       0.242900
               std        0.005178       0.009244       0.008190
recall@3       mean       0.286560       0.295840       0.292680
               std        0.003359       0.013542       0.012729
recall@4       mean       0.326780       0.335240       0.333740
               std        0.005716       0.014708       0.015137
recall@5       mean       0.358740       0.368620       0.371360
               std        0.009051       0.015176       0.018023
recall@10      mean       0.477960       0.488120       0.486040
               std        0.011493       0.013916       0.014409
recall@20      mean       0.605580       0.622620       0.623740
               std        0.007939       0.015058       0.014042
recall@30      mean       0.680800       0.692680       0.695520
               std        0.018719       0.013498       0.013006
recall@50      mean       0.776580       0.780700       0.777460
               std        0.014003       0.011793       0.016716
precision@1    mean       0.237320       0.242820       0.245160
               std        0.007730       0.025852       0.024841
precision@2    mean       0.193700       0.199720       0.200100
               std        0.003712       0.014963       0.014493
precision@3    mean       0.159620       0.167760       0.166660
               std        0.001955       0.012790       0.012842
precision@4    mean       0.139860       0.146700       0.146520
               std        0.002901       0.011335       0.011761
precision@5    mean       0.124800       0.131480       0.132120
               std        0.002558       0.009808       0.010862
precision@10   mean       0.086820       0.090560       0.089960
               std        0.001195       0.005189       0.005545
precision@20   mean       0.057000       0.059940       0.059920
               std        0.000406       0.002535       0.002565
precision@30   mean       0.043680       0.045380       0.045560
               std        0.000753       0.001582       0.001537
precision@50   mean       0.030940       0.031540       0.031420
               std        0.000313       0.000684       0.000841
ndcg@1         mean       0.237320       0.242820       0.245160
               std        0.007730       0.025852       0.024841
ndcg@2         mean       0.262840       0.267580       0.269020
               std        0.005201       0.018530       0.017478
ndcg@3         mean       0.274040       0.282300       0.281700
               std        0.004380       0.018329       0.017941
ndcg@4         mean       0.286740       0.294520       0.294760
               std        0.005078       0.018324       0.018486
ndcg@5         mean       0.297240       0.305700       0.307440
               std        0.005678       0.017957       0.019137
ndcg@10        mean       0.337160       0.345400       0.345380
               std        0.004623       0.017353       0.017226
ndcg@20        mean       0.373600       0.384200       0.385100
               std        0.004224       0.016670       0.017157
ndcg@30        mean       0.393180       0.402640       0.404040
               std        0.004490       0.016683       0.016254
ndcg@50        mean       0.415740       0.423180       0.423300
               std        0.003745       0.015907       0.016879
map@1          mean       0.237320       0.242820       0.245160
               std        0.007730       0.025852       0.024841
map@2          mean       0.235360       0.240040       0.241660
               std        0.005274       0.018838       0.018032
map@3          mean       0.234420       0.241360       0.241740
               std        0.004650       0.018210       0.018078
map@4          mean       0.238320       0.244960       0.245820
               std        0.005010       0.018240       0.018369
map@5          mean       0.241840       0.249160       0.250660
               std        0.005163       0.017970       0.018535
map@10         mean       0.257180       0.264400       0.265120
               std        0.004176       0.017600       0.017615
map@20         mean       0.268620       0.276800       0.277820
               std        0.004233       0.017409       0.017663
map@30         mean       0.273880       0.281980       0.283200
               std        0.003884       0.017539       0.017533
map@50         mean       0.278800       0.286560       0.287540
               std        0.003797       0.017346       0.017551
training_time  mean      14.719971      28.907608      29.941063
               std        6.428711      29.657261      31.717407
num_parameters mean  144448.000000  144448.000000  144448.000000
               std        0.000000       0.000000       0.000000
recall_avg                0.433282       0.441351       0.441351
recall_std                0.214761       0.217326       0.216919
precision_avg             0.119304       0.123989       0.124158
precision_std             0.070715       0.072706       0.073189
ndcg_avg                  0.319762       0.327593       0.328433
ndcg_std                  0.062778       0.063936       0.063676
map_avg                   0.251749       0.258676       0.259858
map_std                   0.017998       0.018905       0.018770

model                scl w/o potential  scl w/o semantic  scl w/o struct
recall@1       mean           0.148680          0.141880        0.144900
               std            0.013896          0.004582        0.005375
recall@2       mean           0.242920          0.240960        0.240200
               std            0.007842          0.004501        0.005747
recall@3       mean           0.292660          0.289580        0.286740
               std            0.012424          0.002924        0.004659
recall@4       mean           0.333620          0.327600        0.329700
               std            0.015121          0.003380        0.006856
recall@5       mean           0.370640          0.361880        0.360400
               std            0.017065          0.008181        0.007761
recall@10      mean           0.486720          0.477640        0.474560
               std            0.015937          0.010113        0.009324
recall@20      mean           0.623080          0.615040        0.606180
               std            0.012829          0.010480        0.009876
recall@30      mean           0.695360          0.690200        0.689900
               std            0.012825          0.007804        0.014046
recall@50      mean           0.777400          0.770520        0.778040
               std            0.016584          0.013348        0.014043
precision@1    mean           0.245040          0.233580        0.236220
               std            0.024593          0.005124        0.008487
precision@2    mean           0.199920          0.194380        0.192480
               std            0.013983          0.002872        0.005864
precision@3    mean           0.166680          0.161620        0.159100
               std            0.012828          0.001597        0.002666
precision@4    mean           0.146520          0.140940        0.140240
               std            0.011710          0.002065        0.002614
precision@5    mean           0.131840          0.126920        0.125060
               std            0.010398          0.002670        0.002235
precision@10   mean           0.090000          0.087500        0.086020
               std            0.005687          0.001629        0.000960
precision@20   mean           0.059840          0.058640        0.056720
               std            0.002443          0.001081        0.000487
precision@30   mean           0.045540          0.044920        0.043920
               std            0.001494          0.000766        0.000638
precision@50   mean           0.031420          0.031060        0.030940
               std            0.000841          0.000219        0.000358
ndcg@1         mean           0.245040          0.233580        0.236220
               std            0.024593          0.005124        0.008487
ndcg@2         mean           0.268900          0.261860        0.261540
               std            0.017054          0.004061        0.007324
ndcg@3         mean           0.281700          0.274680        0.273340
               std            0.017690          0.003266        0.005799
ndcg@4         mean           0.294640          0.286420        0.287300
               std            0.018323          0.003481        0.006349
ndcg@5         mean           0.307080          0.298160        0.297480
               std            0.018546          0.004640        0.006546
ndcg@10        mean           0.345520          0.336820        0.335700
               std            0.017535          0.003846        0.005743
ndcg@20        mean           0.384880          0.376500        0.373260
               std            0.016730          0.004666        0.006151
ndcg@30        mean           0.403920          0.396240        0.394860
               std            0.016034          0.003328        0.006544
ndcg@50        mean           0.423240          0.415340        0.415980
               std            0.016741          0.003769        0.006438
map@1          mean           0.245040          0.233580        0.236220
               std            0.024593          0.005124        0.008487
map@2          mean           0.241540          0.233900        0.234200
               std            0.017612          0.004105        0.007081
map@3          mean           0.241660          0.234020        0.233660
               std            0.017892          0.003909        0.005966
map@4          mean           0.245720          0.237320        0.238100
               std            0.018206          0.003883        0.006193
map@5          mean           0.250440          0.241700        0.241640
               std            0.018145          0.004201        0.006174
map@10         mean           0.265120          0.256640        0.256300
               std            0.017616          0.003282        0.005398
map@20         mean           0.277720          0.269360        0.268120
               std            0.017443          0.003692        0.005584
map@30         mean           0.283080          0.274860        0.273760
               std            0.017313          0.003498        0.005586
map@50         mean           0.287460          0.279160        0.278520
               std            0.017361          0.003384        0.005614
training_time  mean          29.867821         16.444507        9.539985
               std           31.744405          1.802118        1.952927
num_parameters mean      144448.000000     144448.000000   144448.000000
               std            0.000000          0.000000        0.000000
recall_avg                    0.441231          0.435033        0.434513
recall_std                    0.216875          0.216082        0.216291
precision_avg                 0.124089          0.119951        0.118967
precision_std                 0.073147          0.069839        0.070351
ndcg_avg                      0.328324          0.319956        0.319520
ndcg_std                      0.063684          0.064114        0.063332
map_avg                       0.259753          0.251171        0.251169
map_std                       0.018784          0.019002        0.018206

In [12]:
data.to_csv('fn_results4.csv', index=True)